In [2]:
import numpy as np
#creating array from arange 
a=np.arange(15) #single dimension 
a=np.arange(15).reshape(3,5) #multi dimension


In [2]:
a.size

15

In [3]:
a.ndim

2

In [4]:
a.dtype

dtype('int32')

In [5]:
list_b=[1,2,3,4,5,6,7,8,9] #creating array from iterator
b=np.array(list_b).reshape(3,3)

In [6]:
b=np.array([(1.5,2,3),(4,5,6)])

In [8]:
c=np.array([[1,2],[3,4]],dtype=complex)

In [9]:
zeroes=np.zeros((3,4))

In [10]:
ones=np.ones((2,3,4),dtype=np.int16)

In [11]:
cd=np.arange(0,2,0.3)

In [12]:
np.linspace(2,9,3)

array([2. , 5.5, 9. ])

Basic operations

In [13]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a-b

In [14]:
b**2
10*np.sin(a)
a<35

array([ True,  True, False, False])

In [15]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
prod1=A*B
prod2=A@B
prod3=A.dot(B)


In [16]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a*=3
b+=a

In [ ]:
a=np.random.random((2,3))
a.sum()
a.min()
a.max()


In [3]:
np.random.randint(1,10,(4,5,5)) ##3D array

array([[[2, 4, 2, 5, 8],
        [7, 8, 4, 5, 7],
        [9, 9, 3, 3, 6],
        [1, 7, 6, 9, 6],
        [5, 5, 4, 4, 3]],

       [[3, 4, 2, 9, 6],
        [9, 6, 1, 7, 1],
        [5, 8, 5, 3, 5],
        [8, 6, 4, 2, 5],
        [2, 5, 3, 8, 2]],

       [[1, 3, 8, 6, 3],
        [9, 3, 5, 3, 8],
        [6, 6, 8, 7, 1],
        [8, 7, 6, 7, 7],
        [5, 8, 2, 4, 4]],

       [[7, 4, 8, 3, 5],
        [9, 6, 2, 5, 8],
        [9, 7, 5, 6, 1],
        [5, 8, 1, 6, 2],
        [9, 6, 6, 4, 3]]])

In [7]:
rand_arr=np.random.randint(1,100,(4,5))
rand_arr.sum()



1122

In [8]:
rand_arr.min()

2

In [9]:
rand_arr.max()

96

Indexing and Slicing

In [12]:
arr1=np.arange(11,20).reshape(3,3)
arr1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [11]:
arr1[1]

array([14, 15, 16])

In [13]:
arr2=np.arange(1,21).reshape(4,5)

In [14]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
arr2[3,3]

19

In [16]:
arr2[1:4,1]

array([ 7, 12, 17])

In [17]:
arr2.diagonal()

array([ 1,  7, 13, 19])

In [18]:
arr4=np.random.random((4,5))*100

In [19]:
arr4

array([[22.23577241, 69.04569568, 78.55444061, 72.44485181, 46.67244689],
       [16.8205764 , 35.35627906, 71.32261049,  5.59478615, 13.68283509],
       [19.32188551, 16.08094354, 96.45549525, 51.7945594 , 45.67308568],
       [92.5288723 , 88.3938945 , 69.43768614, 84.16357211, 57.77298642]])

In [20]:
np.floor(arr4)

array([[22., 69., 78., 72., 46.],
       [16., 35., 71.,  5., 13.],
       [19., 16., 96., 51., 45.],
       [92., 88., 69., 84., 57.]])

In [21]:
np.ceil(arr4)

array([[23., 70., 79., 73., 47.],
       [17., 36., 72.,  6., 14.],
       [20., 17., 97., 52., 46.],
       [93., 89., 70., 85., 58.]])

In [5]:
arr5=np.arange(1,7).reshape(2,3)
arr6=np.arange(8,14).reshape(2,3)

In [23]:
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr6

array([[ 8,  9, 10],
       [11, 12, 13]])

In [25]:
np.vstack((arr5,arr6))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [26]:
np.hstack((arr5,arr6))

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])

In [6]:
np.hsplit(arr5, 3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [7]:
arr5.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
arr4.T

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr5*2

In [12]:
bool_array = arr5 % 2 == 0

In [13]:
arr5[bool_array]

array([2, 4, 6])

In [14]:
arr5[ arr5 == 2 ]

array([2])

In [15]:
arr5[ arr5 % 2 == 0 ]

array([2, 4, 6])

In [16]:
arr5.trace()

6